#ifndef PERRNO_H
#define PERRNO_H

typedef enum {
	SUCCESS = 0,
	PERRNO_CLEAR = 0, /* Alias for SUCCESS, used to reset error code */

	FAILURE_PLIST_CREATE_CAPACITY_OUT_OF_BOUNDS,
	FAILURE_PLIST_CREATE_NEW_LIST_MALLOC_FAILED,
	FAILURE_PLIST_CREATE_NEW_LIST_DATA_MALLOC_FAILED,

	/* Core List Manipulation Failures (Add/Remove/Resize) */
	FAILURE_PLIST_ADD_NULL_INPUT_LIST, /* Used for all plist_add_* if list is NULL */
	FAILURE_PLIST_ADD_REALLOC_FAILED,

	/* plist_add_str / plist_get_str / plist_set_str Failures */
	FAILURE_PLIST_ADD_NULL_STRING_INPUT,
	FAILURE_PLIST_ADD_STRDUP_FAILED,
	FAILURE_PLIST_GET_STR_NULL_INPUT,
	FAILURE_PLIST_GET_STR_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_STR_NULL_INPUT_OUT_VALUE,
	FAILURE_PLIST_GET_STR_WRONG_TYPE,
	FAILURE_PLIST_GET_STR_STRDUP_FAILED,
	FAILURE_PLIST_SET_STR_NULL_INPUT,
	FAILURE_PLIST_SET_STR_OUT_OF_BOUNDS,
	FAILURE_PLIST_SET_STR_NULL_STRING_INPUT,
	FAILURE_PLIST_SET_STR_STRDUP_FAILED,

	/* plist_add_int / plist_get_int / plist_set_int Failures */
	FAILURE_PLIST_ADD_INT_NULL_INPUT,
	FAILURE_PLIST_GET_INT_NULL_INPUT,
	FAILURE_PLIST_GET_INT_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_INT_WRONG_TYPE,
	FAILURE_PLIST_SET_INT_NULL_INPUT,
	FAILURE_PLIST_SET_INT_OUT_OF_BOUNDS,

	/* plist_add_double / plist_get_double / plist_set_double Failures */
	FAILURE_PLIST_ADD_DOUBLE_NULL_INPUT,
	FAILURE_PLIST_GET_DOUBLE_NULL_INPUT,
	FAILURE_PLIST_GET_DOUBLE_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_DOUBLE_WRONG_TYPE,
	FAILURE_PLIST_SET_DOUBLE_NULL_INPUT,
	FAILURE_PLIST_SET_DOUBLE_OUT_OF_BOUNDS,

	/* plist_add_long / plist_get_long / plist_set_long Failures */
	FAILURE_PLIST_ADD_LONG_NULL_INPUT,
	FAILURE_PLIST_GET_LONG_NULL_INPUT,
	FAILURE_PLIST_GET_LONG_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_LONG_WRONG_TYPE,
	FAILURE_PLIST_SET_LONG_NULL_INPUT,
	FAILURE_PLIST_SET_LONG_OUT_OF_BOUNDS,
	
	/* plist_add_double / plist_get_double / plist_set_double Failures */
	FAILURE_PLIST_ADD_FLOAT_NULL_INPUT,
	FAILURE_PLIST_GET_FLOAT_NULL_INPUT,
	FAILURE_PLIST_GET_FLOAT_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_FLOAT_WRONG_TYPE,
	FAILURE_PLIST_SET_FLOAT_NULL_INPUT,
	FAILURE_PLIST_SET_FLOAT_OUT_OF_BOUNDS,

	/* plist_add_list / plist_get_list / plist_set_list Failures */
	FAILURE_PLIST_ADD_LIST_NULL_INPUT,
	FAILURE_PLIST_ADD_LIST_NULL_LIST_INPUT,
	FAILURE_PLIST_ADD_LIST_PLIST_COPY_FAILED,
	FAILURE_PLIST_GET_LIST_NULL_INPUT,
	FAILURE_PLIST_GET_LIST_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_LIST_NULL_INPUT_OUT_VALUE,
	FAILURE_PLIST_GET_LIST_WRONG_TYPE,
	FAILURE_PLIST_GET_LIST_PLIST_COPY_FAILED,
	FAILURE_PLIST_SET_LIST_NULL_INPUT,
	FAILURE_PLIST_SET_LIST_OUT_OF_BOUNDS,
	FAILURE_PLIST_SET_LIST_NULL_LIST_INPUT,
	FAILURE_PLIST_SET_LIST_PLIST_COPY_FAILED,
	
	/* plist_add_dict plist_get_dict Failures */
	FAILURE_PLIST_ADD_DICT_NULL_INPUT,
	FAILURE_PLIST_ADD_DICT_NULL_DICT_INPUT,
	FAILURE_PLIST_ADD_DICT_PDICT_COPY_FAILED,
	FAILURE_PLIST_GET_DICT_NULL_INPUT,
	FAILURE_PLIST_GET_DICT_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_DICT_WRONG_TYPE,
	FAILURE_PLIST_GET_DICT_NULL_INPUT_OUT_VALUE,
	FAILURE_PLIST_GET_DICT_PDICT_COPY_FAILED,
	FAILURE_PLIST_SET_DICT_NULL_INPUT,
	FAILURE_PLIST_SET_DICT_OUT_OF_BOUNDS,
	FAILURE_PLIST_SET_DICT_NULL_DICT_INPUT,
	FAILURE_PLIST_SET_DICT_PDICT_COPY_FAILED,
	
	/* plist_contains Failures */
	FAILURE_PLIST_CONTAINS_NULL_INPUT,
	
	/* plist_get_type Failures */
	FAILURE_PLIST_GET_TYPE_NULL_INPUT,
	FAILURE_PLIST_GET_TYPE_OUT_OF_BOUNDS,

	/* pvar_equals / pvar_copy Failures */
	FAILURE_PVAR_EQUALS_NULL_INPUT,
	FAILURE_PVAR_EQUALS_UNKNOWN_VAR_TYPE,
	FAILURE_PVAR_COPY_NULL_INPUT,
	FAILURE_PVAR_COPY_STRDUP_FAILED,
	FAILURE_PVAR_COPY_PLIST_COPY_FAILED,
	
	/* plist_copy Failures */
	FAILURE_PLIST_COPY_NULL_INPUT,
	FAILURE_PLIST_COPY_PLIST_CREATE_FAILED,
	FAILURE_PLIST_COPY_PVAR_COPY_FAILED,
	
	/* General plist Failures */
	FAILURE_PLIST_PRINT_NULL_INPUT_LIST,
	FAILURE_PLIST_PRINT_INTERNAL_NULL_INPUT_LIST_DATA,
	FAILURE_PLIST_REMOVE_NULL_INPUT,
	FAILURE_PLIST_REMOVE_OUT_OF_BOUNDS,
	
	/* pdict_create Failures */
	FAILURE_PDICT_CREATE_CAPACITY_OUT_OF_BOUNDS,
	FAILURE_PDICT_CREATE_NEW_DICT_MALLOC_FAILED,
	FAILURE_PDICT_CREATE_NEW_DICT_BUCKETS_MALLOC_FAILED,
	
	/* pdict_entry_copy Failures */
	FAILURE_PDICT_ENTRY_COPY_NULL_INPUT,
	FAILURE_PDICT_ENTRY_COPY_NEW_ENTRY_MALLOC_FAILED,
	FAILURE_PDICT_ENTRY_COPY_PVAR_COPY_FAILED,
	FAILURE_PDICT_ENTRY_COPY_STRDUP_FAILED,
	
	/* pdict_copy Failures */
	FAILURE_PDICT_COPY_NULL_INPUT,
	FAILURE_PDICT_COPY_PDICT_CREATE_FAILED,
	FAILURE_PDICT_COPY_PDICT_ENTRY_COPY_FAILED,
	
	/* pdict_remove Failures */
	FAILURE_PDICT_REMOVE_NULL_INPUT_DICT,
	FAILURE_PDICT_REMOVE_NULL_INPUT_KEY,
	FAILURE_PDICT_REMOVE_KEY_NOT_FOUND,
	
	/* pdict_print pdict_print_internal Failures */
	FAILURE_PDICT_PRINT_INTERNAL_NULL_INPUT,
	FAILURE_PDICT_PRINT_NULL_INPUT,
	
	/* pdict_add_str pdict_get_str pdict_set_str Failures */
	FAILURE_PDICT_ADD_STR_NULL_INPUT_DICT,
	FAILURE_PDICT_ADD_STR_NULL_INPUT_KEY,
	FAILURE_PDICT_ADD_STR_NULL_INPUT_VALUE,
	FAILURE_PDICT_ADD_STR_KEY_EXISTS,
	FAILURE_PDICT_ADD_STR_ENTRY_MALLOC_FAILED,
	FAILURE_PDICT_ADD_STR_KEY_STRDUP_FAILED,
	FAILURE_PDICT_ADD_STR_VALUE_STRDUP_FAILED,
	FAILURE_PDICT_GET_STR_NULL_INPUT_DICT,
	FAILURE_PDICT_GET_STR_NULL_INPUT_KEY,
	FAILURE_PDICT_GET_STR_NULL_INPUT_OUT_VALUE,
	FAILURE_PDICT_GET_STR_WRONG_TYPE,
	FAILURE_PDICT_GET_STR_STRDUP_FAILED,
	FAILURE_PDICT_GET_STR_KEY_NOT_FOUND,
	FAILURE_PDICT_SET_STR_NULL_INPUT_DICT,
	FAILURE_PDICT_SET_STR_NULL_INPUT_KEY,
	FAILURE_PDICT_SET_STR_NULL_INPUT_VALUE,
	FAILURE_PDICT_SET_STR_VALUE_STRDUP_FAILED,
	FAILURE_PDICT_SET_STR_VALUE_NOT_FOUND,
	
	/* pdict_add_int pdict_get_int pdict_set_int Failures */
	FAILURE_PDICT_ADD_INT_NULL_INPUT_DICT,
	FAILURE_PDICT_ADD_INT_NULL_INPUT_KEY,
	FAILURE_PDICT_ADD_INT_KEY_EXISTS,
	FAILURE_PDICT_ADD_INT_ENTRY_MALLOC_FAILED,
	FAILURE_PDICT_ADD_INT_KEY_STRDUP_FAILED,
	FAILURE_PDICT_GET_INT_NULL_INPUT_DICT,
	FAILURE_PDICT_GET_INT_NULL_INPUT_KEY,
	FAILURE_PDICT_GET_INT_NULL_INPUT_OUT_VALUE,
	FAILURE_PDICT_GET_INT_WRONG_TYPE,
	FAILURE_PDICT_GET_INT_KEY_NOT_FOUND,
	FAILURE_PDICT_SET_INT_NULL_INPUT_DICT,
	FAILURE_PDICT_SET_INT_NULL_INPUT_KEY,
	FAILURE_PDICT_SET_INT_VALUE_NOT_FOUND,
	
	/* pdict_add_double pdict_get_double pdict_set_double Failures */
	FAILURE_PDICT_ADD_DOUBLE_NULL_INPUT_DICT,
	FAILURE_PDICT_ADD_DOUBLE_NULL_INPUT_KEY,
	FAILURE_PDICT_ADD_DOUBLE_KEY_EXISTS,
	FAILURE_PDICT_ADD_DOUBLE_ENTRY_MALLOC_FAILED,
	FAILURE_PDICT_ADD_DOUBLE_KEY_STRDUP_FAILED,
	FAILURE_PDICT_GET_DOUBLE_NULL_INPUT_DICT,
	FAILURE_PDICT_GET_DOUBLE_NULL_INPUT_KEY,
	FAILURE_PDICT_GET_DOUBLE_NULL_INPUT_OUT_VALUE,
	FAILURE_PDICT_GET_DOUBLE_WRONG_TYPE,
	FAILURE_PDICT_GET_DOUBLE_KEY_NOT_FOUND,
	FAILURE_PDICT_SET_DOUBLE_NULL_INPUT_DICT,
	FAILURE_PDICT_SET_DOUBLE_NULL_INPUT_KEY,
	FAILURE_PDICT_SET_DOUBLE_VALUE_NOT_FOUND,
	
	/* pdict_add_long pdict_get_long pdict_set_long Failures */
	FAILURE_PDICT_ADD_LONG_NULL_INPUT_DICT,
	FAILURE_PDICT_ADD_LONG_NULL_INPUT_KEY,
	FAILURE_PDICT_ADD_LONG_KEY_EXISTS,
	FAILURE_PDICT_ADD_LONG_ENTRY_MALLOC_FAILED,
	FAILURE_PDICT_ADD_LONG_KEY_STRDUP_FAILED,
	FAILURE_PDICT_GET_LONG_NULL_INPUT_DICT,
	FAILURE_PDICT_GET_LONG_NULL_INPUT_KEY,
	FAILURE_PDICT_GET_LONG_NULL_INPUT_OUT_VALUE,
	FAILURE_PDICT_GET_LONG_WRONG_TYPE,
	FAILURE_PDICT_GET_LONG_KEY_NOT_FOUND,
	FAILURE_PDICT_SET_LONG_NULL_INPUT_DICT,
	FAILURE_PDICT_SET_LONG_NULL_INPUT_KEY,
	FAILURE_PDICT_SET_LONG_VALUE_NOT_FOUND,
	
	/* pdict_add_float pdict_get_float pdict_set_float Failures */
	FAILURE_PDICT_ADD_FLOAT_NULL_INPUT_DICT,
	FAILURE_PDICT_ADD_FLOAT_NULL_INPUT_KEY,
	FAILURE_PDICT_ADD_FLOAT_KEY_EXISTS,
	FAILURE_PDICT_ADD_FLOAT_ENTRY_MALLOC_FAILED,
	FAILURE_PDICT_ADD_FLOAT_KEY_STRDUP_FAILED,
	FAILURE_PDICT_GET_FLOAT_NULL_INPUT_DICT,
	FAILURE_PDICT_GET_FLOAT_NULL_INPUT_KEY,
	FAILURE_PDICT_GET_FLOAT_NULL_INPUT_OUT_VALUE,
	FAILURE_PDICT_GET_FLOAT_WRONG_TYPE,
	FAILURE_PDICT_GET_FLOAT_KEY_NOT_FOUND,
	FAILURE_PDICT_SET_FLOAT_NULL_INPUT_DICT,
	FAILURE_PDICT_SET_FLOAT_NULL_INPUT_KEY,
	FAILURE_PDICT_SET_FLOAT_VALUE_NOT_FOUND,
	
	/* pdict_add_list pdict_get_list pdict_set_list Failures */
	FAILURE_PDICT_ADD_LIST_NULL_INPUT_DICT,
	FAILURE_PDICT_ADD_LIST_NULL_INPUT_KEY,
	FAILURE_PDICT_ADD_LIST_NULL_INPUT_VALUE,
	FAILURE_PDICT_ADD_LIST_KEY_EXISTS,
	FAILURE_PDICT_ADD_LIST_ENTRY_MALLOC_FAILED,
	FAILURE_PDICT_ADD_LIST_KEY_STRDUP_FAILED,
	FAILURE_PDICT_ADD_LIST_VALUE_PLIST_COPY_FAILED,
	FAILURE_PDICT_GET_LIST_NULL_INPUT_DICT,
	FAILURE_PDICT_GET_LIST_NULL_INPUT_KEY,
	FAILURE_PDICT_GET_LIST_NULL_INPUT_OUT_VALUE,
	FAILURE_PDICT_GET_LIST_WRONG_TYPE,
	FAILURE_PDICT_GET_LIST_PLIST_COPY_FAILED,
	FAILURE_PDICT_GET_LIST_KEY_NOT_FOUND,
	FAILURE_PDICT_SET_LIST_NULL_INPUT_DICT,
	FAILURE_PDICT_SET_LIST_NULL_INPUT_KEY,
	FAILURE_PDICT_SET_LIST_NULL_INPUT_VALUE,
	FAILURE_PDICT_SET_LIST_VALUE_PLIST_COPY_FAILED,
	FAILURE_PDICT_SET_LIST_VALUE_NOT_FOUND,
	
	/* pdict_add_dict pdict_get_dict pdict_set_dict Failures */
	FAILURE_PDICT_ADD_DICT_NULL_INPUT_DICT,
	FAILURE_PDICT_ADD_DICT_NULL_INPUT_KEY,
	FAILURE_PDICT_ADD_DICT_NULL_INPUT_VALUE,
	FAILURE_PDICT_ADD_DICT_KEY_EXISTS,
	FAILURE_PDICT_ADD_DICT_ENTRY_MALLOC_FAILED,
	FAILURE_PDICT_ADD_DICT_KEY_STRDUP_FAILED,
	FAILURE_PDICT_ADD_DICT_VALUE_PDICT_COPY_FAILED,
	FAILURE_PDICT_GET_DICT_NULL_INPUT_DICT,
	FAILURE_PDICT_GET_DICT_NULL_INPUT_KEY,
	FAILURE_PDICT_GET_DICT_NULL_INPUT_OUT_VALUE,
	FAILURE_PDICT_GET_DICT_WRONG_TYPE,
	FAILURE_PDICT_GET_DICT_PDICT_COPY_FAILED,
	FAILURE_PDICT_GET_DICT_KEY_NOT_FOUND,
	FAILURE_PDICT_SET_DICT_NULL_INPUT_DICT,
	FAILURE_PDICT_SET_DICT_NULL_INPUT_KEY,
	FAILURE_PDICT_SET_DICT_NULL_INPUT_VALUE,
	FAILURE_PDICT_SET_DICT_VALUE_PDICT_COPY_FAILED,
	FAILURE_PDICT_SET_DICT_VALUE_NOT_FOUND
	
} perrno_t;

extern __thread int pvars_errno;
const char *perror_message(void);

#endif
