#ifndef PERRNO_H
#define PERRNO_H

typedef enum {
	SUCCESS = 0,
	PERRNO_CLEAR = 0, /* Alias for SUCCESS, used to reset error code */

	FAILURE_PLIST_CREATE_CAPACITY_OUT_OF_BOUNDS,
	FAILURE_PLIST_CREATE_NEW_LIST_MALLOC_FAILED,
	FAILURE_PLIST_CREATE_NEW_LIST_DATA_MALLOC_FAILED,

	/* Core List Manipulation Failures (Add/Remove/Resize) */
	FAILURE_PLIST_ADD_NULL_INPUT_LIST, /* Used for all plist_add_* if list is NULL */
	FAILURE_PLIST_ADD_REALLOC_FAILED,

	/* plist_add_str / plist_get_str / plist_set_str Failures */
	FAILURE_PLIST_ADD_NULL_STRING_INPUT,
	FAILURE_PLIST_ADD_STRDUP_FAILED,
	FAILURE_PLIST_GET_STR_NULL_INPUT,
	FAILURE_PLIST_GET_STR_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_STR_WRONG_TYPE,
	FAILURE_PLIST_SET_STR_NULL_INPUT,
	FAILURE_PLIST_SET_STR_OUT_OF_BOUNDS,
	FAILURE_PLIST_SET_STR_NULL_STRING_INPUT,
	FAILURE_PLIST_SET_STR_STRDUP_FAILED,

	/* plist_add_int / plist_get_int / plist_set_int Failures */
	FAILURE_PLIST_ADD_INT_NULL_INPUT,
	FAILURE_PLIST_GET_INT_NULL_INPUT,
	FAILURE_PLIST_GET_INT_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_INT_WRONG_TYPE,
	FAILURE_PLIST_SET_INT_NULL_INPUT,
	FAILURE_PLIST_SET_INT_OUT_OF_BOUNDS,

	/* plist_add_double / plist_get_double / plist_set_double Failures */
	FAILURE_PLIST_ADD_DOUBLE_NULL_INPUT,
	FAILURE_PLIST_GET_DOUBLE_NULL_INPUT,
	FAILURE_PLIST_GET_DOUBLE_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_DOUBLE_WRONG_TYPE,
	FAILURE_PLIST_SET_DOUBLE_NULL_INPUT,
	FAILURE_PLIST_SET_DOUBLE_OUT_OF_BOUNDS,

	/* plist_add_long / plist_get_long / plist_set_long Failures */
	FAILURE_PLIST_ADD_LONG_NULL_INPUT,
	FAILURE_PLIST_GET_LONG_NULL_INPUT,
	FAILURE_PLIST_GET_LONG_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_LONG_WRONG_TYPE,
	FAILURE_PLIST_SET_LONG_NULL_INPUT,
	FAILURE_PLIST_SET_LONG_OUT_OF_BOUNDS,
	
	/* plist_add_double / plist_get_double / plist_set_double Failures */
	FAILURE_PLIST_ADD_FLOAT_NULL_INPUT,
	FAILURE_PLIST_GET_FLOAT_NULL_INPUT,
	FAILURE_PLIST_GET_FLOAT_OUT_OF_BOUNDS,
	FAILURE_PLIST_GET_FLOAT_WRONG_TYPE,
	FAILURE_PLIST_SET_FLOAT_NULL_INPUT,
	FAILURE_PLIST_SET_FLOAT_OUT_OF_BOUNDS,
	
	/* plist_contains Failures */
	FAILURE_PLIST_CONTAINS_NULL_INPUT,

	/* pvar_equals Failures */
	FAILURE_PVAR_EQUALS_NULL_INPUT,
	FAILURE_PVAR_EQUALS_UNKNOWN_VAR_TYPE,
	
	/* General Failures */
	FAILURE_PLIST_PRINT_NULL_INPUT_LIST,
	FAILURE_PLIST_PRINT_NULL_INPUT_LIST_DATA,
	FAILURE_PLIST_REMOVE_NULL_INPUT,
	FAILURE_PLIST_REMOVE_OUT_OF_BOUNDS
	
} perrno_t;

extern __thread int pvars_errno;
const char *perror_message(void);

#endif
